### ISSUE TITLE
大佬，这个有使用数据库把全部权限和资源读取出来？另外保存另外和刷新令牌

### ISSUE THREAD

**Issue by luo199393** [mingyang66/spring-parent#14]
大佬，spring-security-oauth2-server-redis-service项目这个有使用数据库把全部权限和资源读取出来？另外保存另外和刷新令牌

**Comment by luo199393** [comment]
有的话可否给下sql

**Comment by mingyang66** [comment]
留的有口子，你可以在com.yaomy.security.oauth2.provider.UserAuthenticationProvider这个类里面查看如何加载的（spring-security-oauth2-server-redis-service）；
