### ISSUE TITLE
多数据源示例

### ISSUE THREAD

**Issue by meimosor** [mingyang66/spring-parent#29]
我在程序中使用了hibernate多租户，想根据不同租户切换对应的数据源，所以想了解下这个多数据源组件在Spring Data JPA下如何使用

**Comment by mingyang66** [comment]
你可以看下emily-spring-boot-datasource模块实现多数据源切换的逻辑，核心是实现了AbstractRoutingDataSource接口，然后根据ThreadLocal绑定不同的线程来实现多数据源的切换
