### ISSUE TITLE
OAuth2RestTemplate请求不到不抛异常

### ISSUE THREAD

**Issue by superxxl** [mingyang66/spring-parent#4]
password模式
使用OAuth2RestTemplate请求token失败不抛异常，首先，就算失败也不是为null，无法抛自定义异常，因为template未null，.getAccessToken()会抛RuntimeException，无法返回正确的异常信息，敢问大佬是怎么解决的

**Comment by mingyang66** [comment]
我这边测试是可以抛出异常的，如果异常使用try catch 包括 OAuth2AccessToken accessToken = template.getAccessToken();就可以，你可以把你的代码贴出来看下

**Comment by superxxl** [comment]
try catch的话那就有点不优雅
![image](https://user-images.githubusercontent.com/44203516/68751675-f4051680-063c-11ea-9846-ce1f78096af5.png)
堆栈会有额外内存消耗，而且抛的runtimeException，框架应该自带了全局异常捕获，但是优先级比我的高，他会先返回结果出来，而我的全局异常只会再后面抛
